# Generated by Django 3.0.3 on 2020-03-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dt', models.DateTimeField(auto_created=True)),
                ('book_id', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Crawling Un'), (1, 'Crawling Processing'), (2, 'Crawling Success'), (3, 'Crawling Failure')], default=0)),
            ],
        ),
    ]
