# Generated by Django 3.0.3 on 2020-02-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=256)),
                ('novel_id', models.IntegerField()),
                ('content_id', models.IntegerField()),
                ('is_delete', models.BooleanField()),
                ('words', models.IntegerField()),
                ('update_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('intro', models.CharField(max_length=258)),
                ('author', models.CharField(max_length=16)),
                ('category_id', models.IntegerField()),
                ('finished', models.BooleanField(default=False)),
                ('image_url', models.CharField(max_length=128)),
                ('website_id', models.IntegerField(null=True)),
                ('related_id', models.IntegerField(null=True)),
            ],
            options={
                'unique_together': {('title', 'author')},
            },
        ),
    ]
