# Generated by Django 3.0.3 on 2020-02-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='website_id',
            field=models.IntegerField(null=True),
        ),
    ]
