# Generated by Django 3.0.3 on 2020-03-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20200309_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='update_time',
            field=models.DateTimeField(null=True),
        ),
    ]
